import { component } from '@rooted/components'

import styles from './content-notice.css'

export const ContentNotice = component({
	name: 'content-notice-page',
	styles,
	onMount({ append, element }) {
		append(element('div', {
			classes: styles.page,
			children: [
				element('h1', { textContent: 'About this demo' }),
				element('p', {
					classes: styles.lead,
					textContent: 'Recipe Book is an example application built to demonstrate the Rooted framework. It is not a real product and is not affiliated with any food publication or service.',
				}),

				element('h2', { textContent: 'Recipe content' }),
				element('p', {
					textContent: 'All recipes, descriptions, and associated metadata on this site are generated by claude.ai and are not real. Cooking times, ingredient quantities, and techniques have not been verified by a professional. Do not rely on this content for food safety or dietary advice.',
				}),

				element('h2', { textContent: 'Copyright concerns' }),
				element('p', {
					textContent: 'If you believe any content on this site reproduces copyrighted material, please follow these steps:',
				}),
				element('ol', {
					classes: styles.steps,
					children: [
						element('li', {
							children: [
								'Contact ',
								element('a', {
									href: 'https://support.anthropic.com',
									target: '_blank',
									rel: 'noopener noreferrer',
									textContent: 'Anthropic support',
									aria: {
										label: 'Anthropic support (opens in new tab)',
									},
								}),
								' first to report the issue and obtain a support ticket number.',
							],
						}),
						element('li', {
							children: [
								'Once you have your support ticket, open a ',
								element('a', {
									href: 'https://github.com/marvinh-/rooted/issues/new?template=demo-content-copyright.yml',
									target: '_blank',
									rel: 'noopener noreferrer',
									textContent: 'GitHub issue',
									aria: {
										label: 'GitHub issue (opens in new tab)',
									},
								}),
								' and attach your ticket number or link.',
							],
						}),
					],
				}),
				element('p', {
					classes: styles.note,
					textContent: 'Reporting to Anthropic first allows the underlying model behaviour to be reviewed and corrected at its source.',
				}),
			],
		}))
	},
})
