import { component } from '@rooted/components'

import styles from './licenses.css'

export const Licenses = component({
	name: 'licenses-page',
	styles,
	onMount({ append, create }) {
		append(create('div', {
			classes: styles.page,
			children: [
				create('h1', { textContent: 'Licenses' }),
				create('p', {
					classes: styles.lead,
					textContent: 'Recipe Book is an open-source demo application. The following third-party materials are used.',
				}),

				create('h2', { textContent: 'Rooted framework' }),
				create('p', {
					children: [
						'The ',
						create('a', {
							href: 'https://github.com/Marvin-Brouwer/rooted',
							target: '_blank',
							rel: 'noopener noreferrer',
							textContent: 'Rooted framework',
						}),
						' is released under the MIT License.',
					],
				}),

				create('h2', { textContent: 'Hero photograph' }),
				create('p', {
					children: [
						'The banner photograph is sourced from ',
						create('a', {
							href: 'https://unsplash.com/photos/cooked-food-R02KgL5Ti3Y',
							target: '_blank',
							rel: 'noopener noreferrer',
							textContent: 'Unsplash',
						}),
						' and is used under the Unsplash License, which permits free use without requiring attribution.',
					],
				}),

				create('h2', { textContent: 'Recipe content' }),
				create('p', {
					children: [
						'All recipe text was generated by ',
						create('a', {
							href: 'https://anthropic.com',
							target: '_blank',
							rel: 'noopener noreferrer',
							textContent: 'Claude (Anthropic)',
						}),
						'. Content is provided for demonstration purposes only and has not been verified by a professional.',
					],
				}),

				create('h2', { textContent: 'Application source' }),
				create('p', {
					children: [
						'The Recipe Book source code is part of the ',
						create('a', {
							href: 'https://github.com/Marvin-Brouwer/rooted/tree/main/examples/recipe-book',
							target: '_blank',
							rel: 'noopener noreferrer',
							textContent: 'Rooted monorepo',
						}),
						' and is released under the MIT License.',
					],
				}),
			],
		}))
	},
})
