import { component } from '@rooted/components'

import styles from './licenses.css'

export const Licenses = component({
	name: 'licenses-page',
	styles,
	onMount({ append, element }) {
		append(
			element('div', {
				classes: styles.page,
				children: [
					element('h1', { textContent: 'Licenses' }),
					element('p', {
						classes: styles.lead,
						textContent: 'Recipe Book is an open-source demo application. The following third-party materials are used.',
					}),

					element('h2', { textContent: 'Rooted framework' }),
					element('p', {
						children: [
							'The ',
							element('a', {
								href: 'https://github.com/Marvin-Brouwer/rooted',
								target: '_blank',
								rel: 'noopener noreferrer',
								textContent: 'Rooted framework',
							}),
							' is released under the MIT License.',
						],
					}),

					element('h2', { textContent: 'Hero photograph' }),
					element('p', {
						children: [
							'The banner photograph is sourced from ',
							element('a', {
								href: 'https://unsplash.com/photos/cooked-food-R02KgL5Ti3Y',
								target: '_blank',
								rel: 'noopener noreferrer',
								textContent: 'Unsplash',
							}),
							' and is used under the Unsplash License, which permits free use without requiring attribution.',
						],
					}),

					element('h2', { textContent: 'Recipe content' }),
					element('p', {
						children: [
							'All recipe text was generated by ',
							element('a', {
								href: 'https://anthropic.com',
								target: '_blank',
								rel: 'noopener noreferrer',
								textContent: 'Claude (Anthropic)',
							}),
							'. Content is provided for demonstration purposes only and has not been verified by a professional.',
						],
					}),

					element('h2', { textContent: 'Application source' }),
					element('p', {
						children: [
							'The Recipe Book source code is part of the ',
							element('a', {
								href: 'https://github.com/Marvin-Brouwer/rooted/tree/main/examples/recipe-book',
								target: '_blank',
								rel: 'noopener noreferrer',
								textContent: 'Rooted monorepo',
							}),
							' and is released under the MIT License.',
						],
					}),
				],
			}),
		)
	},
})
