packages:
  - packages/*
  - packages/adapters/*
  - tooling/*
  - examples/*

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - "esbuild"
  - "keytar"
  - "sharp"
  - "unrs-resolver"

overrides:
  "source-map@0.8.0-beta.0": "0.7.4"
  "sourcemap-codec": "npm:@jridgewell/sourcemap-codec@^1.4.15"

allowedDeprecatedVersions:
  "glob": "11"

peerDependencyRules:
  allowedVersions:
    'vite-plugin-pwa>vite': '8'

patchedDependencies:
  semantic-release@25.0.8: patches/semantic-release@25.0.8.patch