packages:
  - packages/*
  - packages/adapters/*
  - tooling/*
  - examples/*

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - "esbuild"
  - "keytar"
  - "sharp"
  - "unrs-resolver"
