import type { Plugin, ResolvedConfig } from 'vite'
import { glob } from 'tinyglobby'
import { writeFile, mkdir } from 'node:fs/promises'
import { resolve, relative, dirname } from 'node:path'

/**
 * Options for {@link generateRouteManifest}.
 */
type Options = {
	/**
	 * Glob pattern (relative to the Vite project root) used to discover gate
	 * files. Matched files are re-exported from the aggregator.
	 *
	 * @example `'./src/**\/_gates.mts'`
	 */
	glob: string
	/**
	 * Path (relative to the Vite project root) where the aggregator file is
	 * written. This file is auto-generated — add it to `.gitignore`.
	 *
	 * @example `'./src/_routes.g.mts'`
	 */
	root: string
}

/**
 * Vite plugin that auto-discovers `_gates.mts` files and writes a single
 * aggregator module that re-exports all named gate exports.
 *
 * The aggregator can be spread directly into {@link router}:
 *
 * ```ts
 * import * as appRoutes from './_routes.g.mts'
 * const Router = router({ home, notFound, ...appRoutes })
 * ```
 *
 * **Behaviour:**
 * - Regenerates the aggregator on every `buildStart`.
 * - In dev mode, adding or removing a `_gates.mts` file triggers regeneration
 *   and a full page reload via Vite HMR.
 * - Exports are sorted alphabetically to produce a stable file on each run.
 *
 * @param options - Glob pattern and output path.
 * @returns A Vite {@link Plugin}.
 *
 * @example `vite.config.ts`
 * ```ts
 * import { generateRouteManifest } from '@rooted/router/manifest'
 *
 * export default defineConfig({
 *   plugins: [
 *     generateRouteManifest({
 *       glob: './src/**\/_gates.mts',
 *       root: './src/_routes.g.mts',
 *     }),
 *   ],
 * })
 * ```
 *
 * @see {@link router}
 * @see {@link gate}
 */
export function generateRouteManifest(options: Options): Plugin {
	let config: ResolvedConfig

	async function generate() {
		const files = await glob(options.glob, { cwd: config.root, absolute: false })
		const rootPath = resolve(config.root, options.root)
		const rootDir = dirname(rootPath)

		const lines = [
			'// generated by generateRouteManifest — do not edit',
			...files.sort().map(file => {
				const rel = relative(rootDir, resolve(config.root, file))
				const importPath = rel.startsWith('.') ? rel : `./${rel}`
				return `export * from '${importPath.split('\\').join('/')}'`
			}),
			'',
		]

		await mkdir(rootDir, { recursive: true })
		await writeFile(rootPath, lines.join('\n'), 'utf-8')
	}

	return {
		name: 'rooted:generate-route-manifest',

		configResolved(resolved) { config = resolved },

		async buildStart() { await generate() },

		configureServer(server) {
			const onAddOrUnlink = async (filePath: string) => {
				const rel = relative(config.root, filePath).split('\\').join('/')
				const matched = await glob(options.glob, { cwd: config.root })
				if (!matched.includes(rel) && !filePath.endsWith('/_gate.mts')) return
				await generate()
				const rootPath = resolve(config.root, options.root)
				const mod = server.moduleGraph.getModuleById(rootPath)
				if (mod) server.moduleGraph.invalidateModule(mod)
				server.hot.send({ type: 'full-reload' })
			}
			server.watcher.on('add', onAddOrUnlink)
			server.watcher.on('unlink', onAddOrUnlink)
		},
	}
}
