import type { Plugin, ResolvedConfig } from 'vite'
import { glob } from 'tinyglobby'
import { writeFile, mkdir } from 'node:fs/promises'
import { resolve, relative, dirname } from 'node:path'

type Options = {
	glob: string
	root: string
}

export function generateRouteManifest(options: Options): Plugin {
	let config: ResolvedConfig

	async function generate() {
		const files = await glob(options.glob, { cwd: config.root, absolute: false })
		const rootPath = resolve(config.root, options.root)
		const rootDir = dirname(rootPath)

		const lines = [
			'// generated by generateRouteManifest — do not edit',
			...files.sort().map(file => {
				const rel = relative(rootDir, resolve(config.root, file))
				const importPath = rel.startsWith('.') ? rel : `./${rel}`
				return `export * from '${importPath.split('\\').join('/')}'`
			}),
			'',
		]

		await mkdir(rootDir, { recursive: true })
		await writeFile(rootPath, lines.join('\n'), 'utf-8')
	}

	return {
		name: 'rooted:generate-route-manifest',

		configResolved(resolved) { config = resolved },

		async buildStart() { await generate() },

		configureServer(server) {
			const onAddOrUnlink = async (filePath: string) => {
				const rel = relative(config.root, filePath).split('\\').join('/')
				const matched = await glob(options.glob, { cwd: config.root })
				if (!matched.includes(rel) && !filePath.endsWith('/_gate.mts')) return
				await generate()
				const rootPath = resolve(config.root, options.root)
				const mod = server.moduleGraph.getModuleById(rootPath)
				if (mod) server.moduleGraph.invalidateModule(mod)
				server.hot.send({ type: 'full-reload' })
			}
			server.watcher.on('add', onAddOrUnlink)
			server.watcher.on('unlink', onAddOrUnlink)
		},
	}
}
