import type { Plugin, ResolvedConfig } from 'vite'
import { glob } from 'tinyglobby'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { resolve, relative, dirname } from 'node:path'
import { createHash } from 'node:crypto'

import packageJson from '../../package.json' assert { is: 'json' }

const pluginName = 'vite-plugin:generate-rooted-route-manifest'

/**
 * Options for {@link generateRouteManifest}.
 */
type Options = {
	/**
	 * Glob pattern (relative to the Vite project root) used to discover gate
	 * files. Matched files are re-exported from the aggregator.
	 *
	 * @example `'./src/**\/_routes.mts'`
	 */
	glob: string
	/**
	 * Path (relative to the Vite project root) where the aggregator file is
	 * written. This file is auto-generated — add it to `.gitignore`.
	 *
	 * @example `'./src/_routes.g.mts'`
	 */
	root: string,
	/**
	 * Export name for the generated manifest
	 *
	 * @example `'appRoutes'`
	 * @default `'appRoutes'`
	 */
	routeExport?: string
}

/**
 * Vite plugin that auto-discovers `_routes.mts` files and writes a single
 * aggregator module that re-exports all named gate exports.
 *
 * The aggregator can be spread directly into {@link router}:
 *
 * ```ts
 * import * as appRoutes from './_routes.g.mts'
 * const Router = router({ home, notFound, ...appRoutes })
 * ```
 *
 * **Behaviour:**
 * - Regenerates the aggregator on every `buildStart`.
 * - In dev mode, adding or removing a `_routes.mts` file triggers regeneration
 *   and a full page reload via Vite HMR.
 * - Exports are sorted alphabetically to produce a stable file on each run.
 *
 * @param options - Glob pattern and output path.
 * @returns A Vite {@link Plugin}.
 *
 * @example `vite.config.ts`
 * ```ts
 * import { generateRouteManifest } from '@rooted/router/manifest'
 *
 * export default defineConfig({
 *   plugins: [
 *     generateRouteManifest({
 *       glob: './src/**\/_routes.mts',
 *       root: './src/_routes.g.mts',
 *     }),
 *   ],
 * })
 * ```
 *
 * @see {@link router}
 * @see {@link route}
 */
export function generateRouteManifest(options: Options): Plugin {
	let config: ResolvedConfig

	async function generate() {
		const files = (await glob(options.glob, { cwd: config.root, absolute: false })).toSorted()
		const rootPath = resolve(config.root, options.root)
		const rootDir = dirname(rootPath)

		const globForComment = options.glob.replaceAll('*', '∗')

		const lines = [
			'/* @refresh reload */',
			'/* eslint-disable */',
			'// @ts-nocheck',
			'',
			'/**',
			' * @generated -- AUTO-GENERATED FILE -- DO NOT EDIT',
			' * Changes may be overwritten.',
			' *',
			` * Generated by: ${pluginName} version: ${packageJson.version}`,
			` * Sources: ${globForComment}`,
			` * Hash: ${hash(files, packageJson.version)}`,
			' *',
			` * Regenerate by running the build pipeline.`,
			` * Updates automatically in watch mode.`,
			' */',
			'',
			`import { RouteDefinition } from '@rooted/router'`,
			'',
			...files.map((file) => {
				const rel = relative(rootDir, resolve(config.root, file))
				const importPath = rel.startsWith('.') ? rel : `./${rel}`
				return `/** @__PURE__ */ const gate_${getFileId(file)} = () => /** @__PURE__ */ import('${importPath.split('\\').join('/')}').then(rename, '${getFileId(file)}')`
			}),
			'',
			'type RouteModule = RouteDefinition<unknown, Array<unknown>>',
			'type RouteModules = Record<string, RouteModule>',
			'',
			'/** @__PURE__ */',
			'function rename(gates: RouteModules, hash: string) {',
			'\treturn Object.fromEntries(Object',
			'\t\t.entries(gates)',
			'\t\t.filter(([key]) => key !== `default`)',
			'\t\t.map(([key, value]) => [`R${hash}_${key}`, value])',
			'\t)',
			'}',
			'',
			`/**`,
			' * ### Generated route manifest',
			' *',
			' * Automatically generated route manifest, \\',
			` * contains all routes discovered using the \`${globForComment}\` convention.`,
			` *`,
			` * _Regenerate by running the build pipeline. \\`,
			` * Updates automatically in watch mode._`,
			` *`,
			` * @example Used for spreading into a router`,
			' * ```ts',
			` * router({ home, notFound, ...appRoutes })`,
			' * ```',
			' *',
			' * @__PURE__',
			` */`,
			`export const ${options.routeExport ?? 'appRoutes'}: RouteModules = /** @__PURE__ */ Object.freeze(`,
			...files.map((file) => `\tawait gate_${getFileId(file)},`),
			`)`,
			'',
		]

		const generatedManifest = lines.join('\n')
		await mkdir(rootDir, { recursive: true })

		const originalManifest = await readExistingManifest(rootPath)
		if (originalManifest === generatedManifest) {
			console.debug('Code change did not require manifest update.')
			return
		}
		await writeFile(rootPath, generatedManifest, 'utf-8')
	}

	return {
		name: pluginName,

		configResolved(resolved) { config = resolved },

		async buildStart() { await generate() },

		configureServer(server) {
			const onAddOrUnlink = async (filePath: string) => {
				const rel = relative(config.root, filePath).split('\\').join('/')
				const matched = await glob(options.glob, { cwd: config.root })
				if (!matched.includes(rel) && !filePath.endsWith('/_gate.mts')) return
				await generate()
				const rootPath = resolve(config.root, options.root)
				const mod = server.moduleGraph.getModuleById(rootPath)
				if (mod) server.moduleGraph.invalidateModule(mod)
				server.hot.send({ type: 'full-reload' })
			}
			server.watcher.on('add', onAddOrUnlink)
			server.watcher.on('unlink', onAddOrUnlink)
		},
	}
}


export function hash(files: string[], version: string): string {
	const hash = createHash("sha256")

	hash.update(version)
	for (const file of files) {
		hash.update(file)
	}

	return hash.digest("hex")
}

const getFileId = (path: string) => createHash('md5').update(path).digest('hex').slice(0, 8)

async function readExistingManifest(rootPath: string) {
	try {
		return await readFile(rootPath, 'utf-8')
	}
	catch {
		return undefined
	}
}