import { component } from '@rooted/components'
import { href, Link } from '@rooted/router'

import { ContentNoticeRoute } from '../content/_routes.mts'

import styles from './content-banner.css'

export const ContentBanner = component({
	name: 'content-banner',
	styles,
	onMount({ append, create }) {
		const label = create('section', {
			role: 'note',
			classes: styles.screenReaderNotice,
			children: [
				create('p', {
					children: [
						'This is a demo application and not a real product.',
						create('br'),
						'All recipe content on this site is generated by Claude and is not real.',
					],
				}),
			],
		})

		const banner = create('div', {
			classes: styles.banner,
			role: 'region',
			ariaLabelledByElements: [label],
			children: [
				create('span', { classes: styles.badge, textContent: 'Demo app' }),
				create('span', {
					classes: styles.text,
					children: [
						'This is an example app \u2014 all recipe content is generated by Claude and not real. ',
						create(Link, {
							href: href.for(ContentNoticeRoute),
							classes: styles.link,
							children: 'Learn more',
						}),
					],
				}),
			],
		})

		append(label, banner)
	},
})
